CREATE TABLE IF NOT EXISTS tb_driver(
    company_id int not null,
    resale_id int not null,
    id int not null AUTO_INCREMENT,
    status tinyint not null,
    name varchar(100) not null,
    cpf varchar(11) not null,
    rg varchar(11) not null,
    date_birth datetime not null,
    male_female tinyint not null,
    cnh_register varchar(11) not null,
    cnh_category varchar(10) not null,
    cnh_validation datetime not null,
    email varchar(100),
    ddd_cellphone varchar(2),
    cellphone varchar(9),
    ddd_phone varchar(2),
    phone varchar(8),
    zip_code varchar(8) not null,
    state varchar(2) not null,
    city varchar(100) not null,
    neighborhood varchar(100) not null,
    address varchar(100) not null,
    address_number varchar(10) not null,
    address_complement varchar(100),
    photo_driver longblob,
    photo_doc1 longblob,
    photo_doc2 longblob,
    user_id int not null,
    user_name varchar(100) not null,
    date_register datetime not null,
    FOREIGN KEY(company_id) REFERENCES tb_company(id),
    FOREIGN KEY(resale_id) REFERENCES tb_resale(id),
    FOREIGN KEY(user_id) REFERENCES tb_user(id),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS tb_vehicle_entry_new(
    company_id int not null,
    resale_id int not null,
    id int not null AUTO_INCREMENT,
    status tinyint not null,
    step_entry tinyint not null,
    budget_status tinyint not null,
    id_user_entry int not null,
    name_user_entry varchar(100) not null,
    date_entry datetime not null,
    date_prevision_exit datetime,
    user_id_exit int,
    user_name_exit varchar(100),
    date_exit datetime,
    id_user_attendant int,
    name_user_attendant varchar(100),
    id_user_exit_auth1 int,
    name_user_exit_auth1 varchar(100),
    date_exit_auth1 datetime,
    id_user_exit_auth2 int,
    name_user_exit_auth2 varchar(100),
    date_exit_auth2 datetime,
    status_auth_exit tinyint not null,
    model_id int,
    model_description varchar(100),
    client_company_id int,
    client_company_name varchar(255),
    client_company_cnpj varchar(14),
    client_company_cpf varchar(11),
    client_company_rg varchar(11),
    driver_entry_id int,
    driver_entry_name varchar(255) not null,
    driver_entry_cpf varchar(11),
    driver_entry_rg varchar(11),
    driver_entry_photo longblob,
    driver_entry_signature longblob,
    driver_entry_photo_doc1 longblob,
    driver_entry_photo_doc2 longblob,
    driver_exit_id int,
    driver_exit_name varchar(255),
    driver_exit_cpf varchar(11),
    driver_exit_rg varchar(11),
    driver_exit_photo longblob,
    driver_exit_signature longblob,
    driver_exit_photo_doc1 longblob,
    driver_exit_photo_doc2 longblob,
    color tinyint,
    placa varchar(7),
    placas_junto varchar(255),
    frota varchar(10),
    vehicle_new tinyint not null,
    km_entry varchar(10),
    km_exit varchar(10),
    photo1 longblob,
    photo2 longblob,
    photo3 longblob,
    photo4 longblob,
    quantity_extinguisher int,
    quantity_traffic_cone int,
    quantity_tire int,
    quantity_tire_complete int,
    quantity_tool_box int,
    service_order tinyint not null,
    num_service_order varchar(20),
    num_nfe varchar(20),
    num_nfse varchar(20),
    information varchar(255),
    information_concierge varchar(255),
    FOREIGN KEY(company_id) REFERENCES tb_company(id),
    FOREIGN KEY(resale_id) REFERENCES tb_resale(id),
    FOREIGN KEY(id_user_entry) REFERENCES tb_user(id),
    FOREIGN KEY(id_user_attendant) REFERENCES tb_user(id),
    FOREIGN KEY(id_user_exit_auth1) REFERENCES tb_user(id),
    FOREIGN KEY(id_user_exit_auth2) REFERENCES tb_user(id),
    FOREIGN KEY(model_id) REFERENCES tb_vehicle_model(id),
    FOREIGN KEY(client_company_id) REFERENCES tb_client_company(id),
    FOREIGN KEY(driver_entry_id) REFERENCES tb_driver(id),
    FOREIGN KEY(driver_exit_id) REFERENCES tb_driver(id),
    PRIMARY KEY(id)
 );

 INSERT INTO tb_vehicle_entry_new
 (`company_id`, `resale_id`, `id`, `status`, `step_entry`, `budget_status`, `id_user_entry`, `name_user_entry`, `date_entry`, `date_prevision_exit`, `user_id_exit`, `user_name_exit`, `date_exit`, `id_user_attendant`, `name_user_attendant`, `id_user_exit_auth1`, `name_user_exit_auth1`, `date_exit_auth1`, `id_user_exit_auth2`, `name_user_exit_auth2`, `date_exit_auth2`, `status_auth_exit`, `model_id`, `model_description`, `client_company_id`, `client_company_name`, `client_company_cnpj`, `client_company_cpf`, `client_company_rg`, `driver_entry_name`, `driver_entry_cpf`, `driver_entry_rg`, `driver_entry_photo`, `driver_entry_signature`, `driver_entry_photo_doc1`, `driver_entry_photo_doc2`, `driver_exit_name`, `driver_exit_cpf`, `driver_exit_rg`, `driver_exit_photo`, `driver_exit_signature`, `driver_exit_photo_doc1`, `driver_exit_photo_doc2`, `color`, `placa`, `placas_junto`, `frota`, `vehicle_new`, `km_entry`, `km_exit`, `photo1`, `photo2`, `photo3`, `photo4`, `quantity_extinguisher`, `quantity_traffic_cone`, `quantity_tire`, `quantity_tire_complete`, `quantity_tool_box`, `service_order`, `num_service_order`, `num_nfe`, `num_nfse`, `information`, `information_concierge`)
 SELECT
 `company_id`, `resale_id`, `id`, `status`, `step_entry`, `budget_status`, `id_user_entry`, `name_user_entry`, `date_entry`, `date_prevision_exit`, `user_id_exit`, `user_name_exit`, `date_exit`, `id_user_attendant`, `name_user_attendant`, `id_user_exit_auth1`, `name_user_exit_auth1`, `date_exit_auth1`, `id_user_exit_auth2`, `name_user_exit_auth2`, `date_exit_auth2`, `status_auth_exit`, `model_id`, `model_description`, `client_company_id`, `client_company_name`, `client_company_cnpj`, `client_company_cpf`, `client_company_rg`, `driver_entry_name`, `driver_entry_cpf`, `driver_entry_rg`, `driver_entry_photo`, `driver_entry_signature`, `driver_entry_photo_doc1`, `driver_entry_photo_doc2`, `driver_exit_name`, `driver_exit_cpf`, `driver_exit_rg`, `driver_exit_photo`, `driver_exit_signature`, `driver_exit_photo_doc1`, `driver_exit_photo_doc2`, `color`, `placa`, `placas_junto`, `frota`, `vehicle_new`, `km_entry`, `km_exit`, `photo1`, `photo2`, `photo3`, `photo4`, `quantity_extinguisher`, `quantity_traffic_cone`, `quantity_tire`, `quantity_tire_complete`, `quantity_tool_box`, `service_order`, `num_service_order`, `num_nfe`, `num_nfse`, `information`, `information_concierge`
 FROM `tb_vehicle_entry`;

 ALTER TABLE tb_vehicle_entry RENAME TO tb_vehicle_entry_old;
 ALTER TABLE tb_vehicle_entry_new RENAME TO tb_vehicle_entry;

 SET FOREIGN_KEY_CHECKS = 0;
 DROP TABLE tb_vehicle_entry_old;
 SET FOREIGN_KEY_CHECKS = 1;
