package com.concierge.apiconcierge.dtos.vehicle.entry;

import com.concierge.apiconcierge.models.budget.enums.StatusBudgetEnum;
import com.concierge.apiconcierge.models.enums.YesNot;
import com.concierge.apiconcierge.models.vehicle.enums.*;
import jakarta.persistence.Column;
import jakarta.persistence.Lob;

import java.util.Date;

public record VehicleEntryDto(
        Integer companyId,
        Integer resaleId,
        Integer id,
        StatusVehicleEnum status,
        StepVehicleEnum stepEntry,
        StatusBudgetEnum budgetStatus,
        Integer idUserEntry,
        String nameUserEntry,
        Date dateEntry,
        byte[] entryPhoto1,
        byte[] entryPhoto2,
        byte[] entryPhoto3,
        byte[] entryPhoto4,
        Date datePrevisionExit,

        Integer userIdExit,
        String userNameExit,
        Date dateExit,
        byte[] exitPhoto1,
        byte[] exitPhoto2,
        byte[] exitPhoto3,
        byte[] exitPhoto4,
        String exitInformation,

        Integer idUserAttendant,
        String nameUserAttendant,
        byte[] photo1,
        byte[] photo2,
        byte[] photo3,
        byte[] photo4,

        Integer idUserExitAuth1,
        String nameUserExitAuth1,
        Date dateExitAuth1,
        Integer idUserExitAuth2,
        String nameUserExitAuth2,
        Date dateExitAuth2,
        StatusAuthExitEnum statusAuthExit,
        Integer modelId,
        String modelDescription,
        Integer clientCompanyId,
        String clientCompanyName,
        String clientCompanyCnpj,
        String clientCompanyCpf,
        String clientCompanyRg,
        Integer driverEntryId,
        String driverEntryName,
        String driverEntryCpf,
        String driverEntryRg,
        byte[] driverEntryPhoto,
        byte[] driverEntrySignature,
        byte[] driverEntryPhotoDoc1,
        byte[] driverEntryPhotoDoc2,
        Integer driverExitId,
        String driverExitName,
        String driverExitCpf,
        String driverExitRg,
        byte[] driverExitPhoto,
        byte[] driverExitSignature,
        byte[] driverExitPhotoDoc1,
        byte[] driverExitPhotoDoc2,
        ColorVehicleEnum color,
        String placa,
        String placasJunto,
        String frota,
        YesNot vehicleNew,
        String kmEntry,
        String kmExit,

        Integer quantityExtinguisher,
        Integer quantityTrafficCone,
        Integer quantityTire,
        Integer quantityTireComplete,
        Integer quantityToolBox,
        YesNot serviceOrder,
        String numServiceOrder,
        String numNfe,
        String numNfse,
        String information,
        String informationConcierge) {
}
